server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///cloud?useUnicode=true&characterEcoding=utf-8&useSSL=false
    password: 123456
    username: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.cloud.entities
